- README.md
Add first information to readme
> Update README.md to reflect new course mission 

- .gitignore
Related to: https://github.com/jhudsl/OTTR_Template/issues/580#issuecomment-1287250410
> Delete spell_check_results.tsv from the gitignore

- 01-intro.Rmd
- 05-submission.Rmd
- Appendix.Rmd
- index.Rmd
- resources/dictionary.txt
Images added for "what is scientific data" and "what are good excuses not to share"
> Add images to the introduction

- 01-intro.Rmd
- 04-writing_a_DMS_plan.Rmd
- About.Rmd
- Appendix.Rmd
- References.Rmd
- _bookdown.yml
- book.bib
- resources/dictionary.txt
@carriewright11  Below are a few minor formatting things I didn't notice on review. Sorry about that!
I've also added a few citations that people can reference to the "Writing the plan" section.
Also, what do you think about trying to format across 'Writing a DMS Plan' kind of like a checklist? 
EDIT:
Resolves #19 (thanks @carriewright11 !)
> Minor formatting and adding a few refs people can cite

- 01-intro.Rmd
- assets/style.css
- also involved modifying the css to add just a gray block for details sections
> adding section about proprietary data with gray background 

- 03-budgeting.Rmd
> Adding figure

- 01-intro.Rmd
- README.md
- index.Rmd
Adding the new images. @ehumph does this lead into the more complicated image OK? or do you think we need a bit more.
> Images intro

- 01-intro.Rmd
I am adding links from the Key Questions to their answers. This addresses issue #25 to make a slightly easier user experience.
> Add links from key questions to answers in intro

- 02-data_management_plan.Rmd
This adds a size estimate for fcs data files, based on what a researcher said on Slack.
> Update file size table in data management plan chapter

- 01-intro.Rmd
- 03-budgeting.Rmd
- 04-writing_a_DMS_plan.Rmd
- 05-submission.Rmd
- resources/dictionary.txt
I went through all of the documents from Sandy and added additional information.
> Sandy updates

- 01-intro.Rmd
- 02-data_management_plan.Rmd
- 03-budgeting.Rmd
- 04-writing_a_DMS_plan.Rmd
- 05-submission.Rmd
- resources/ignore-urls.txt
resolves #40 
Adding all the path images.
Fixing some small formatting things I noticed.
> Formatting and pathway images

- About.Rmd
Adds the authors and contributors, thus resolving issue #51
> Add authors - resolves #51

- 02-data_management_plan.Rmd
- 04-writing_a_DMS_plan.Rmd
Realized in searching for metabolomics repositories that sometimes the links people need are not in the interactive table and so I want to emphasize that they should look in the other links that NIH provided too.
I also added a bit more about data management - linking people to the appendix and the computing course in case people need that. I used the image about phones as motivation for that so I moved that up from the repository section.
I also added a summary at the end with all the links
> More repos

- 01-intro.Rmd
- 04-writing_a_DMS_plan.Rmd
- 05-submission.Rmd
I wanted to see if I could fix the main rendering issue because I thought based on a slack comment from @cansavvy that Github's issues might be the reason for those errors, but I noticed we are still getting them I figured I would try a pull request just to see if that fixed it, because maybe the rendering is still caught on out -of-date info. 
I also found what the deal is for renewals on the website so I'm adding that to the course to fill out that section. Thus this resolves #48
> Adding grant renewal section and more question boxes

- Appendix.Rmd
- resources/dictionary.txt
resolves #72 
- add DMPtool and other resources to the appendix
> adding JHU resources

- About.Rmd
Resolves #77 
- want to link more people out to info about them
- added some more people
- added more credit to the style section
Need to verify that Sandy is good with this link
> adding more links and credits

- README.md
- index.Rmd
added the disclaimer to the first page
> adding disclaimer

- 01-intro.Rmd
- 04-writing_a_DMS_plan.Rmd
- Appendix.Rmd
- index.Rmd
resolves #83  and resolves #81  and resolves #79 and resolves #82 
- saying no hyperlinks in overall takeaways
- saying no hyperlinks in writing section
Anywhere else we need to? Is it emphatic enough? This thing Jeff sent is kinda intense: https://nexus.od.nih.gov/all/2023/01/10/dms-plan-tip-leave-the-hypertext-at-home/
> addressing recent issues

- _output.yml
Doing a bit of learning on the fly.  Sorry all!!  I THINK this should actually get the analytics going.
> OK ACTUALLY adding analytics now. 

- 04-writing_a_DMS_plan.Rmd
- Appendix.Rmd
- book.bib
- resources/dictionary.txt
- Resolves #86
- Fixes one of the citations (It appears not to have been added to the `book.bib`)
- Adds reference to AnVIL (link to terra blog post)
- Removes emoji checkmark from `04-writing_a_DMS_plan.Rmd` as this was triggering a spell check fail
> Adding resources, add links (#86), fix reference

- 00-app.Rmd
- 04-writing_a_DMS_plan.Rmd
- _bookdown.yml
- child/_child_dms_app.Rmd
- Adding a page so that folks can easily find the app at https://dmshelper.fredhutch.org/
- Adding a callout box to the app in the writing section
- Also noticed the repo name was incorrect in `_bookdown.yml`
> Add page about DMS Helper App

- index.Rmd
I was adding this course and the AI course to the [ITN website](https://www.itcrtraining.org/courses) and wanted to make it consistent with how we have audience and content images... so I made an audience image. I also added a link to the slides.
> Audience image

- .github/workflows/render-all.yml
- config_automation.yml
Update some of the rendering permissions :)
> Update render all workflow

- 01-intro.Rmd
- quizzes/quiz_1.md
Still working on getting Leanpub to recognize all the chapters
> Remove question marks so that leanpub interprets them correctly

- quizzes/quiz_2.md
Too many mandatory incorrect answers 😨
> Fix issue with quiz

- 01-intro.Rmd
- index.Rmd
Changes:
- Added "Introduction Summary" video : [youtube](https://youtu.be/XQkmYWhpQ2s), [slides](https://docs.google.com/presentation/d/1JfBhHqzDINLatLDraKILOoTZW1gDctuP_wcK0ebxRMw/edit?usp=sharing)
- Add a reflection on the value of data sharing
> Expand Introduction with videos

- 01-intro.Rmd
- config_automation.yml
- quizzes/quiz_1.md
Adding in videos, for Coursera fanciness: 
- How will the plan affect me? : [Slides](https://docs.google.com/presentation/d/1Mx8ADm6Y_MxaHNfLYbl1cTlonzsZlbAcI5IIs1TawdY/edit?usp=sharing), [YouTube](https://youtu.be/TZbA_IloRdQ).
- Introduction wrap up: [Slides](https://docs.google.com/presentation/d/16rHzAr5kXabGeseLQdbEHEazKMK7Fo1OEXQtzNSZqhE/edit?usp=sharing), [YouTube](https://youtu.be/9h6EvNDoKVo).
> Adding in another video for the introduction

- 04-writing_a_DMS_plan.Rmd
Removing a video section that was duplicated
> Remove redundant video

- 01-intro.Rmd
Resolves #121 
Nathan Boyd let us know about this link from writing our data management course.
This now points more directly to the table.
> fixing link to table for activity codes
